/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppointmentDialog: typeof import('./src/components/AppointmentDialog.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    Hero: typeof import('./src/components/Hero.vue')['default']
    JobCard: typeof import('./src/components/JobCard.vue')['default']
    LoginDialog: typeof import('./src/components/LoginDialog.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    ProfessionalList: typeof import('./src/components/ProfessionalList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UpcomingAppointments: typeof import('./src/components/UpcomingAppointments.vue')['default']
  }
}
